CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                   NVARCHAR (128) NOT NULL,
    [Email]                NVARCHAR (256) NULL,
    [EmailConfirmed]       BIT            NOT NULL,
    [PasswordHash]         NVARCHAR (MAX) NULL,
    [SecurityStamp]        NVARCHAR (MAX) NULL,
    [PhoneNumber]          NVARCHAR (MAX) NULL,
    [PhoneNumberConfirmed] BIT            NOT NULL,
    [TwoFactorEnabled]     BIT            NOT NULL,
    [LockoutEndDateUtc]    DATETIME       NULL,
    [LockoutEnabled]       BIT            NOT NULL,
    [AccessFailedCount]    INT            NOT NULL,
    [UserName]             NVARCHAR (256) NOT NULL,
    [NormalizedUserName] NVARCHAR(256) NULL, 
    [NormalizedEmail] NVARCHAR(256) NULL, 
    [ConcurrencyStamp] NVARCHAR(max) NULL, 
    [LockoutEnd] datetimeoffset NULL, 
    [Surname] NVARCHAR(256) NOT NULL, 
    [FirstName] NVARCHAR(256) NOT NULL, 
    [LastName] NVARCHAR(256) NULL, 
    [Address] NVARCHAR(MAX) NULL, 
    [Balance] DECIMAL(18, 2) NOT NULL, 
    [AvatarName] NVARCHAR (132) NULL,
    [LanguageId] INT NOT NULL, 
    CONSTRAINT [PK_dbo.AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);