CREATE TABLE [dbo].[Message]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[SenderId] NVARCHAR(128) NOT NULL,
	[ReceiverId] NVARCHAR(128) NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	[Date] DATETIMEOFFSET NOT NULL,
)
