CREATE TABLE [dbo].[Review]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[UserId] NVARCHAR(128) NOT NULL,
	[Text] NVARCHAR(MAX) NOT NULL,
	[IsAnonymous] BIT NOT NULL,
	[IsHidden] BIT NOT NULL,
)
