CREATE TABLE [dbo].[Venue]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(MAX) NOT NULL,
    [ImageName] NVARCHAR(132) NOT NULL,
	[Location] NVARCHAR(MAX) NOT NULL,
	[QrCodeId] NVARCHAR(128) NOT NULL,
)
